server:
  port: 8090


spring:
  # JPA Setting
  jpa:
    hibernate:
      #ddl ?? ?? ?? ??
      ddl-auto: create  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        diarect: org.hibernate.dialect.H2Dialect  # ??? ??? ?? ?????? ??? ?????.
        show_sql: true  # sql ??? ?????.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql ??? ????? ?????.

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            #log level
            sql: trace  # query? ?? ?? ?? ????? ??? ? ?? ?????. TRACE Log? ?? ?????.